apps/curso/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.curso.views import *

app_name = 'curso'

urlpatterns = [
    path('', login_required(Listview.as_view()), name='cursos'),
    path('/', login_required(ListviewAperutar.as_view()), name='aperturar'),

]

sigestscolar/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps import backEnd
from apps.curso.views import IngresoNotasView, PrintActaNotas, PrintActaInscritos
from apps.empresa.views import EmpresaView
from apps.profesor.distributivodocente import Listview
from apps.rubro.views import ListviewValores, ListviewFacturacion, PrintFactura

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('login/', backEnd.LoginFormView.as_view(), name='login'),
                  path('', backEnd.LoginFormView.as_view(), name='index'),
                  path('accounts/login', backEnd.LoginFormView.as_view(), name='login_next'),
                  path('logout/', backEnd.disconnect, name='logout'),
                  path('dashborad/', login_required(backEnd.DashboardView.as_view()), name='dashborad'),
                  path('empresa/', login_required(EmpresaView.as_view()), name='empresa'),
                  path('change_profile/<int:pk>', login_required(backEnd.UserChangeGroup.as_view()), name='changeprofile'),
                  path('cursos/', include('apps.curso.urls', namespace='cursos')),
                  path('paralelos/', include('apps.paralelo.urls', namespace='paralelos')),
                  path('materias/', include('apps.materia.urls', namespace='materias')),
                  path('productos/', include('apps.producto.urls', namespace='productos')),
                  path('periodos/', include('apps.periodo.urls', namespace='periodos')),
                  path('externos/', include('apps.externo.urls', namespace='externos')),
                  path('administrativos/', include('apps.administrativo.urls', namespace='administrativos')),
                  path('docentes/', include('apps.profesor.urls', namespace='profesor')),
                  path('alumnos/', include('apps.alumno.urls', namespace='alumnos')),
                  path('inscripciones/', include('apps.inscripcion.urls', namespace='inscripciones')),
                  path('distributivo/', login_required(Listview.as_view()), name='distributivo'),
                  path('valores', login_required(ListviewValores.as_view()), name='valores'),
                  path('facturacion', login_required(ListviewFacturacion.as_view()), name='facturacion'),
                  path('exportcomprobante/<int:pk>', login_required(PrintFactura.as_view()), name='imprimirfactura'),
                  path('notas', login_required(IngresoNotasView.as_view()), name='notas'),
                  path('generaractaindividual/<int:pk>', login_required(PrintActaNotas.as_view()), name='generaractanotas'),
                  path('listaalumnos/<int:pk>', login_required(PrintActaInscritos.as_view()), name='lsitaalumnos'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/curso/models.py
from django.db import models
from django.db.models import Avg
from django.forms import model_to_dict

from apps.extras import ModeloBase, PrimaryKeyEncryptor
from apps.materia.models import Materia
from apps.paralelo.models import Paralelo
from apps.periodo.models import PeriodoLectivo
from apps.profesor.models import Profesor
from sigestscolar.settings import SECRET_KEY_ENCRIPT


class Curso(ModeloBase):
    nombre = models.CharField(default='', max_length=200, verbose_name=u'Nombre')
    descripcion = models.CharField(default='', max_length=200, verbose_name=u'Descripcion del curso')

    def __str__(self):
        return '{}'.format(self.nombre)

    class Meta:
        verbose_name = u"Curso"
        verbose_name_plural = u"Cursos"
        ordering = ['nombre']
        unique_together = ('nombre',)

    def to_JSON(self):
        item = model_to_dict(self)
        return item

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper().strip()
        super(Curso, self).save(*args, **kwargs)


class CursoParalelo(ModeloBase):
    curso = models.ForeignKey(Curso, on_delete=models.PROTECT)
    paralelo = models.ManyToManyField(Paralelo)
    periodo = models.ForeignKey(PeriodoLectivo, on_delete=models.PROTECT)
    cupo = models.IntegerField(default=5)
    cupoindividual = models.BooleanField(default=False)
    quimestres = models.IntegerField(default=0, verbose_name='Numero de Quimestres')
    parciales = models.IntegerField(default=0, verbose_name='Numero de Parciales')

    def __str__(self):
        return '{} - {}'.format(self.periodo.nombre, self.curso.nombre)

    def to_JSON(self):
        item = model_to_dict(self)
        item['curso'] = self.curso.to_JSON()
        return item

    def tiene_inscripciones(self):
        return self.inscripcion_set.all().exists()

    def total_inscritos(self):
        return self.inscripcion_set.all().count()

    def total_materias(self):
        return self.cursomateria_set.all().count()

    def materias_asignadas_curso(self, id=None):
        data = []
        keys = []
        for m in self.cursomateria_set.filter(status=True):
            if id is not None:
                if m.id == id:
                    data.append({'id': m.id, 'materia': m.materia.nombre, 'select': 'true'})
                else:
                    data.append({'id': m.id, 'materia': m.materia.nombre, 'select': 'false'})
            # elif m == self.cursomateria_set.filter(status=True)[0]:
            #     data.append({'id': m.id, 'materia': m.materia.nombre, 'select': True})
            else:
                for p in m.curso.paralelo.filter(status=True):
                    if not MateriaAsignada.objects.filter(materia=m, paralelo=p).exists():
                        if m.materia.id not in keys:
                            keys.append(m.materia.id)
                            data.append({'id': m.id, 'materia': m.materia.nombre, 'select': len(keys) == 1})
        return data

    def get_paralelos(self, id=None):
        data = []
        keys = []
        for p in self.paralelo.filter(status=True):
            if id is not None:
                if p.id == id:
                    data.append({'id': p.id, 'paralelo': p.nombre, 'select': 'true'})
                else:
                    data.append({'id': p.id, 'paralelo': p.nombre, 'select': 'false'})
            # elif p == self.paralelo.filter(status=True)[0]:
            #     data.append({'id': p.id, 'paralelo': p.nombre, 'select': True})
            else:
                for c in CursoMateria.objects.filter(curso__periodo=self.periodo, curso=self):
                    if not MateriaAsignada.objects.filter(materia=c, paralelo=p).exists():
                        if p.id not in keys:
                            keys.append(p.id)
                            data.append({'id': p.id, 'paralelo': p.nombre, 'select': len(keys) == 1})
        return data

    def encoded_id(self):
        return PrimaryKeyEncryptor(SECRET_KEY_ENCRIPT).encrypt(self.id)

    def cupos_disponible(self):
        return self.total_inscritos() < self.cupo_total()

    def configuracion_valores(self):
        if self.configuracionvalorescurso_set.exists():
            return self.configuracionvalorescurso_set.first()
        return False

    def configuro_quimestres(self):
        if CursoQuimestre.objects.filter(status=True, cursoasignado__materia__curso=self).exists():
            return CursoQuimestre.objects.filter(status=True, cursoasignado__materia__curso=self).count() == (
                        self.quimestres * (self.parciales + 1)) * (
                       self.paralelo.count()) * self.cursomateria_set.count()
        return False

    def cupo_total(self):
        if self.cupoindividual:
            return self.cupo * self.paralelo.all().count()
        return self.cupo

    def cupo_individual(self):
        if self.cupoindividual:
            return self.cupo

    def cupo_disponible_por_paralelo(self, paralelo):
        if self.cupoindividual:
            return self.cupo_individual() > self.inscripcion_set.filter(paralelo_id=paralelo).count()

    class Meta:
        verbose_name = u"Curso Paralelo"
        verbose_name_plural = u"Cursos Paralelos"
        ordering = ['periodo']


class CursoMateria(ModeloBase):
    curso = models.ForeignKey(CursoParalelo, on_delete=models.PROTECT)
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT)

    def __str__(self):
        return '{} - {} '.format(self.curso.curso.nombre, self.materia.nombre)

    def to_JSON(self):
        item = model_to_dict(self)
        item['curso'] = self.curso.to_JSON()
        item['materia'] = model_to_dict(self.materia)
        return item

    def docentes(self):
        self.materiaasignada_set.filter(status=True)

    class Meta:
        verbose_name = u"Curso Materia"
        verbose_name_plural = u"Cursos Materias"
        ordering = ['materia']


class ConfiguracionValoresCurso(ModeloBase):
    curso = models.ForeignKey(CursoParalelo, on_delete=models.PROTECT)
    matricula = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    pension = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    numeropensiones = models.IntegerField(default=1)


class ConfiguracionValoresGeneral(ModeloBase):
    matricula = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    pension = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    numeropensiones = models.IntegerField(default=1)


class MateriaAsignada(ModeloBase):
    profesor = models.ForeignKey(Profesor, on_delete=models.PROTECT)
    materia = models.ForeignKey(CursoMateria, on_delete=models.PROTECT)
    paralelo = models.ForeignKey(Paralelo, on_delete=models.PROTECT)

    def __str__(self):
        return '{} {}'.format(self.profesor.persona.nombre_completo(), self.materia.materia.nombre)

    def modelo_eval_quimestres(self):
        return self.cursoquimestre_set.filter(status=True).distinct('parcial__quimestre')

    def modelo_eval_parcial(self):
        return self.cursoquimestre_set.filter(status=True).distinct('parcial')

    def modelo_eval_parcial_total(self):
        return int(self.cursoquimestre_set.filter(status=True).distinct(
            'parcial').count() / self.modelo_eval_quimestres().count())

    def modelo_eval_parcial_totalacta(self):
        return int(self.cursoquimestre_set.filter(status=True).distinct(
            'parcial').count() / self.modelo_eval_quimestres().count()) + 1

    def puede_exportar_acta(self):
        return self.cursoquimestre_set.filter(status=True).first().tiene_notas()


class Quimestre(ModeloBase):
    nombre = models.CharField(default='', max_length=200, verbose_name=u'Nombre')
    numero = models.IntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.nombre)


TIPO_PARCIAL = (
    (0, 'PARCIAL'),
    (1, 'EXAMEN')
)


class ModeloParcial(ModeloBase):
    quimestre = models.ForeignKey(Quimestre, on_delete=models.PROTECT)
    nombre = models.CharField(default='', max_length=200, verbose_name=u'Nombre')
    tipo = models.IntegerField(choices=TIPO_PARCIAL, default=0, verbose_name=u'Nombre')
    numero = models.IntegerField(default=1)

    def __str__(self):
        return '{} {} {} {}'.format(self.numero, self.quimestre, self.nombre, self.get_tipo_display())


class CursoQuimestre(ModeloBase):
    cursoasignado = models.ForeignKey(MateriaAsignada, on_delete=models.PROTECT, verbose_name='Curso y Materia')
    parcial = models.ForeignKey(ModeloParcial, on_delete=models.PROTECT, verbose_name='Quimestre y Parcial', null=True,
                                blank=True)
    actacerrada = models.BooleanField(default=False)

    def __str__(self):
        return '{} {}'.format(self.cursoasignado.materia.curso, self.cursoasignado.materia)

    def tiene_notas(self):
        return self.notasalumno_set.filter(status=True).exists()

    def alumnos_notas(self):
        return self.notasalumno_set.filter(status=True)


class NotasAlumno(ModeloBase):
    curso = models.ForeignKey(CursoQuimestre, on_delete=models.PROTECT, verbose_name='Curso Quimestre parcial')
    alumno = models.ForeignKey('inscripcion.Inscripcion', on_delete=models.PROTECT,
                               verbose_name='Inscripcion de Alumno')
    nota = models.DecimalField(decimal_places=2, max_digits=5, default=0, verbose_name='Nota')

    def __str__(self):
        return '{} {}'.format(self.curso, self.alumno, self.nota)

    # def promedio_parciales(self, quimestre, materia):
    #     promedio = NotasAlumno.objects.filter(curso__parcial__quimestre=quimestre,
    #                                           curso__cursoasignado=materia, alumno=self).aggregate(promedio=Avg('nota'))
    #     return promedio

templates/curso/form.html
{% extends 'bases/base_form.html' %}
{% block extra_form %}
    <hr>
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title"><i class="fas fa-book"></i><b> Materias a impartir</b></h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <label for="id_materias">Busca una materia: </label>
                    <select name="materias" id="id_materias" class="form-control select2">
                    </select>
                    <br>
                    <div class="form-group">
                        <table class="table table-bordered" id="table_materias">
                            <thead>
                            <tr>
                                <th style="width: 5%">#</th>
                                <th style="width:15%;">Identificacion</th>
                                <th style="width: 50%;">Nombre</th>
                                <th style="width: 20%">Alias</th>
                                <th style="width: 10%">Quitar</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <!-- /.form-group -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.card-body -->
    </div>
{% endblock %}
{% block sumbit_form %}
{% endblock %}
{% block validate_form %}
    <script>
        var tblmaterias;
        var apertura = {
            items: {
                periodo: '',
                cupo: '',
                cupoindividual: '',
                parciales: '',
                quimestres: '',
                curso: '',
                paralelo: '',
                materias: [],
            },
            get_ids: function () {
                var ids = [];
                $.each(this.items.materias, function (key, value) {
                    ids.push(value.id);
                });
                return ids;
            },
            add: function (data) {
                this.items.materias.push(data);
                this.list();
            },
            list: function () {
                tblmaterias = $("#table_materias").DataTable({
                    destroy: true,
                    dom: 't',
                    autoWidth: false,
                    dataSrc: "",
                    responsive: true,
                    language: {
                        "url": '//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json'
                    },
                    data: this.items.materias,
                    columns: [
                        {data: "id"},
                        {data: "identificacion"},
                        {data: "nombre"},
                        {data: "alias"},
                        {data: "id"}
                    ],
                    columnDefs: [
                        {
                            targets: [-1],
                            class: 'text-center',
                            width: '5%',
                            orderable: false,
                            render: function (data, type, row) {
                                {#console.log(row);#}
                                return '<a rel="remove" type="button" class="btn btn-danger btn-xs btn-flat rounded-pill" style="color: white" data-toggle="tooltip" title="Quitar Producto"><i class="fa fa-times"></i></a>';

                            }
                        }
                    ]
                });
            },
        };
        $(function () {
            $('#id_curso').select2({
                language: {
                    inputTooShort: function () {
                        return "Ingresa al menos un caracter...";
                    },
                    "noResults": function () {
                        return "Sin resultados";
                    },
                    "searching": function () {
                        return "Buscando...";
                    }
                },
                theme: 'bootstrap4',
                allowClear: true,
                ajax: {
                    delay: 250,
                    type: 'GET',
                    url: '/cursos/aperturar/',
                    data: function (params) {
                        return {
                            term: params.term,
                            action: 'search_curso',
                            id: $('#id_periodo option:selected').val()
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };

                    },

                },
                placeholder: 'Busca un Curso',
                minimumInputLength: 1,
            });
            $('#id_paralelo').select2({
                language: {
                    inputTooShort: function () {
                        return "Ingresa al menos un caracter...";
                    },
                    "noResults": function () {
                        return "Sin resultados";
                    },
                    "searching": function () {
                        return "Buscando...";
                    }
                },
                theme: 'bootstrap4',
                allowClear: true,
                ajax: {
                    delay: 250,
                    type: 'GET',
                    url: '/cursos/aperturar/',
                    data: function (params) {
                        return {
                            term: params.term,
                            action: 'search_paralelo',
                            id: $('#id_periodo option:selected').val()
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };

                    },

                },
                placeholder: 'Busca un Paralelo',
                minimumInputLength: 1,
            });
            $('#id_materias').select2({
                language: {
                    inputTooShort: function () {
                        return "Ingresa al menos un caracter...";
                    },
                    "noResults": function () {
                        return "Sin resultados";
                    },
                    "searching": function () {
                        return "Buscando...";
                    }
                },
                theme: 'bootstrap4',
                allowClear: true,
                ajax: {
                    delay: 250,
                    type: 'GET',
                    url: '/cursos/aperturar/',
                    data: function (params) {
                        return {
                            term: params.term,
                            action: 'search_materias',
                            ids: JSON.stringify(apertura.get_ids())
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };

                    },

                },
                placeholder: 'Busca una materia',
                minimumInputLength: 1,
            }).on('select2:select', function (e) {
                $.ajax({
                    type: "GET",
                    url: '/cursos/aperturar/',
                    data: {
                        "id": $('#id_materias option:selected').val(),
                        'action': 'get_materia'
                    },
                    dataType: 'json',
                    success: function (data) {
                        apertura.add(data);
                        $('#id_materias').val(null).trigger('change');
                    },
                    error: function (xhr, status, data) {
                        alert(data);
                    },

                })
            });
            $('#table_materias').on('click', 'a[rel="remove"]', function () {
                var tr = tblmaterias.cell($(this).closest('td, li')).index();
                borrar_todo_alert('Alerta de Eliminación',
                    'Esta seguro que desea eliminar esta materia <br> ' +
                    '<strong>CONTINUAR?</strong>', function () {
                        apertura.items.materias.splice(tr.row, 1);
                        apertura.list();
                    })
            });
            validador();
            $("#form").validate({
                rules: {
                    periodo: {required: true,},
                    paralelo: {required: true},
                    curso: {required: true},
                    cupo: {required: true, cupominimo:true},
                    quimestres: {required: true},
                    parciales: {required: true},
                },
                messages: {
                    periodo: {required: "Por favor elige un periodo"},
                    paralelo: {required: "Por favor elige un paralelo"},
                    curso: {required: "Por favor elige un curso"},
                    cupo: {required: "Por favor ingresa un cupo"},
                    quimestres: {required: "Por favor ingresa un numero de quimestre valido",
                    max:'Numero maximo 5',
                    min:'Numero minimo 2'
                    },
                    parciales: {required: "Por favor ingresa un numero de parcial valido",
                    max:'Numero maximo 5',
                    min:'Numero minimo 3'}
                },
            });
            $('[data-toggle="tooltip"]').tooltip();
            $('#form').on('submit', function (e) {
                e.preventDefault();
                if ($(this).valid() && apertura.items.materias.length > 0) {
                    apertura.items.curso = $('#id_curso').val();
                    apertura.items.paralelo = $('#id_paralelo').val();
                    apertura.items.periodo = $('#id_periodo').val();
                    apertura.items.cupo = $('#id_cupo').val();
                    apertura.items.cupoindividual = $('#id_cupoindividual').is(':checked');
                    apertura.items.parciales = $('#id_parciales').val();
                    apertura.items.quimestres = $('#id_quimestres').val();
                    var parametros = {'apertura': JSON.stringify(apertura.items)};
                    parametros['action'] = '{{ action }}';
                     {% if pk %}parametros['pk'] = '{{ pk }}';{% endif %}
                    save_with_ajax('Estas seguro?', '/cursos/aperturar/', 'Desea guardar esta informacion?', parametros,
                        function (e) {
                            menssaje_ok('Todo correcto!', 'Informacion guardada corectamente!', 'success', function (e) {
                                window.location.replace('/cursos/aperturar/');
                            })

                        })
                } else {
                    menssaje_error('Error', 'Debes ingresar al menos 3 materias a impartir para aperturar el curso', 'error', function () {
                    })
                }

            });
            {% if materias %}
                {% for materia in materias %}
                    apertura.items.materias.push({{ materia|safe }});
                {% endfor %}
            {% endif %}
            apertura.list();
        });


    </script>

{% endblock %}